sudo: required
services:
  - docker

before_install:
  - docker build -t devandrews/cicd -f Dockerfile.dev .

script:
  - docker run -e CI=true devandrews/cicd npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "cicd"
  env: "Cicd-env"
  bucket_name: "elasticbeanstalk-us-east-1-930470676495"
  bucket_path: "cicd"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY